name: garmin-sports-sync

on:
  workflow_dispatch:
  ## schedule:
    ## - cron: '30 23,0,1,2,7,8,9 * * *'
    ## - cron: '30 23,0 * * *'
env:
  GITHUB_NAME: elingsoft
  GITHUB_EMAIL: wangzb@elingsoft.com
  AESKEY: ${{ secrets.AESKEY }}
  SOURCE_GARMIN_AUTH_DOMAIN: ${{ secrets.SOURCE_GARMIN_AUTH_DOMAIN }}
  SOURCE_GARMIN_EMAIL: ${{ secrets.SOURCE_GARMIN_EMAIL }}
  SOURCE_GARMIN_PASSWORD: ${{ secrets.SOURCE_GARMIN_PASSWORD }}
  SYNC_GARMIN_AUTH_DOMAIN: ${{ secrets.SYNC_GARMIN_AUTH_DOMAIN }}  
  SYNC_GARMIN_EMAIL:  ${{ secrets.SYNC_GARMIN_EMAIL }}
  SYNC_GARMIN_PASSWORD:  ${{ secrets.SYNC_GARMIN_PASSWORD }}
  WEBDAV_URL:  ${{ secrets.WEBDAV_URL }}
  WEBDAV_USERNAME:  ${{ secrets.WEBDAV_USERNAME }}
  WEBDAV_PASSWORD:  ${{ secrets.WEBDAV_PASSWORD }}
  LOCAL_OR_WEBDAV: ${{ secrets.LOCAL_OR_WEBDAV }}
  
  ## 通知推送配置
  # 企业微信机器人
  QYWX_KEY:  ${{ secrets.QYWX_KEY }}
  
  # 叮叮机器人
  DD_BOT_SECRET:  ${{ secrets.DD_BOT_SECRET }}
  DD_BOT_TOKEN:  ${{ secrets.DD_BOT_TOKEN }}

  
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.2"
    # from pdm
    - name: Set Variables
      id: set_variables
      run: |
        echo "::set-output name=PY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
        echo "::set-output name=PIP_CACHE::$(pip cache dir)"
    - name: Cache PIP
      uses: actions/cache@v2
      with:
        path: ${{ steps.set_variables.outputs.PIP_CACHE }}
        key: Ubuntu-pip-${{ steps.set_variables.outputs.PY }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      if: steps.pip-cache.outputs.cache-hit != 'true'
    - name: Run Garmin Sync
      run: |
        python scripts/garmin/garmin_sync.py
    - name: Push new cookie
      run: |
        git config --local user.email "${{ env.GITHUB_EMAIL }}"
        git config --local user.name "${{ env.GITHUB_NAME }}"
        git add .
        git commit -m 'update garmin cookie' || echo "nothing to commit"
        git push || echo "nothing to push"
